name:                raw-proxy
version:             0.1.0.0
github:              "nlv/raw-proxy"
license:             BSD3
author:              "Leon Nikitin"
maintainer:          "nlvomsk@gmail.com"
copyright:           "Leon Nikitin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nlv/raw-proxy#readme>

dependencies:
- base >= 4.7 && < 5
- http-reverse-proxy
- conduit-extra
- text
- optparse-applicative


library:
  source-dirs: src

executables:
  raw-proxy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raw-proxy

tests:
  raw-proxy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raw-proxy
